name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [sonarr, radarr, prowlarr, bazarr, jellyfin-web, jellyfin]
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: cachix/install-nix-action@v31.11.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v17
        with:
          name: arr-packages
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build .#packages.x86_64-linux.${{ matrix.package }} -L
