name: build

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [sonarr, radarr, prowlarr, bazarr, jellyfin-web, jellyfin]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@02b16339eddcf6ea27126a830c7f1992855cae13 # v17
        with:
          name: arr-packages
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix build .#packages.x86_64-linux.${{ matrix.package }} -L
